server:
  port: 8081
spring:
  application:
    name: hmdp
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${Mashiro.mysql.host}:${Mashiro.mysql.port}/${Mashiro.mysql.database}?useSSL=false&serverTimezone=UTC
    username: ${Mashiro.mysql.username}
    password: ${Mashiro.mysql.password}
  redis:
    host: ${Mashiro.redis.host}
    port: ${Mashiro.redis.port}
    database: ${Mashiro.redis.database}
    password: ${Mashiro.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug